version: '3.9'

services:
  redisearch:
    image: redis/redis-stack-server:latest
    container_name: redisearch
    ports:
      - "6379:6379"
    networks:
      - book_network
  
  goapp: 
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - redisearch
    networks:
      - book_network
        
volumes:
  redis_data:

networks:
  book_network:
    driver: bridge